version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c0vxszw27hui"
s3_prefix = "example2"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
